AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Yodata API middleware for {env}.yodata.me
  repository=yodata/solid-serverless/packages/api-middleware

Globals:
  Function:
    Timeout: 3
    Runtime: nodejs8.10
    Tags:
      app: solid-serverless
      component: api-middleware
    Environment:
      Variables:
        NODE_ENV: development
        CHECK_SCOPE_FUNCTION_NAME: check-scope
        CREATE_VIEW_FUNCTION_NAME: data-processing-service-create-view
        DEFAULT_JSONLD_CONTEXT: 'https://dev.yodata.io/public/real-estate/context.json'

Resources:
  ApiMiddlewareFn:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: index.handler
      FunctionName: api-middleware
    Policies:
      - LambdaInvokePolicy:
          FunctionName: 'check-scope'

Outputs:
  ApiMiddlewareFn:
    Description: api-middleware service arn
    Value: !GetAtt ApiMiddlewareFn.Arn

  ApiMiddlewareFnIamRole:
    Description: api-middleware service role
    Value: !GetAtt ApiMiddlewareFnRole.Arn
