AWSTemplateFormatVersion: '2010-09-09'
Description: Yodata API middleware for dev.yodata.io
Globals:
  Function:
    Environment:
      Variables:
        APPLY_POLICY_FUNCTION_NAME: apply-policy
        CHECK_SCOPE_FUNCTION_NAME: check-scope
        CREATE_VIEW_FUNCTION_NAME: data-processing-service-create-view
        DEBUG_LEVEL: debug
        DEFAULT_JSONLD_CONTEXT: https://dev.yodata.io/public/real-estate/context.json
        NODE_ENV: development
    Runtime: nodejs8.10
    Tags:
      app: solid-serverless
      component: api-middleware
    Timeout: 5
Resources:
  ApiMiddlewareFn:
    Policies:
    - AWSLambdaExecute
    Properties:
      AutoPublishAlias: next
      CodeUri: s3://yodata-solid-serverless-api-middleware/8e6479a5ccbaafdb8e4ac5a2a43e5be2
      FunctionName: api-middleware
      Handler: index.handler
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
