AWSTemplateFormatVersion: '2010-09-09'
Description: Data Processing Services
Globals:
  Function:
    Runtime: nodejs8.10
    Tags:
      app: solid-serverless
      component: data-processing
Resources:
  checkScope:
    Properties:
      CodeUri: s3://yodata-solid-serverless-data-processing-service/2fae51c3da6652b8ba9e5d2305f60f57
      Description: Validates data with ACL.scope and data policies, returns a ValidateAction
      FunctionName: data-processing-service-check-scope
      Handler: check-scope.handler
    Type: AWS::Serverless::Function
  createView:
    Properties:
      CodeUri: s3://yodata-solid-serverless-data-processing-service/2fae51c3da6652b8ba9e5d2305f60f57
      Description: Applies data policies and ACL.scope to create consumer specific
        views of data
      FunctionName: data-processing-service-create-view
      Handler: create-view.handler
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
