AWSTemplateFormatVersion: '2010-09-09'
Description: 'Data validation, transformation, etc... Last Modified: December 15,
  2018 Author: Dave Duran <dave@yodata.io>

  '
Globals:
  Function:
    Runtime: nodejs8.10
    Tags:
      app: solid-serverless
      component: data-processing
Outputs:
  CreateViewService:
    Description: Applies ACL Scope & Pod Data Policies
    Value:
      Fn::GetAtt:
      - CreateViewService
      - Arn
  CreateViewServiceRole:
    Description: Implicit IAM Role for data-processing-service-create-view
    Value:
      Fn::GetAtt:
      - CreateViewServiceRole
      - Arn
Resources:
  CheckScopeService:
    Properties:
      CodeUri: s3://yodata-solid-serverless-data-processing-service/c3f4b314f3bcb3d725ffc8fb33a035a7
      Description: Validates data with ACL.scope and data policies, returns a ValidateAction
      FunctionName: data-processing-service-check-scope
      Handler: index.checkScope
    Type: AWS::Serverless::Function
  CreateViewService:
    Properties:
      CodeUri: s3://yodata-solid-serverless-data-processing-service/c3f4b314f3bcb3d725ffc8fb33a035a7
      Description: Applies data policies and ACL.scope to create consumer specific
        views of data
      FunctionName: data-processing-service-create-view
      Handler: index.createView
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
