env:
  es6: true
  node: true
  jest/globals: true
extends: 'standard'
parserOptions:
  ecmaVersion: 2022
rules:
  indent:
    - error
    - tab
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
  no-tabs:
    - off
plugins:
  - jest
