#!/usr/bin/env bash
set -e

echo "######################################################"
echo "#"
echo "# YoData - Solid Serverless - Dev Docker Environment"
echo "#"
echo "######################################################"
echo "HOME: $HOME"
echo "PWD: $(pwd)"
echo "Initial PATH: $PATH"

. "$HOME/src/scripts/setEnv"

echo "Environment PATH: $PATH"
echo "------------------------------------------------------"
echo

bash || true
