AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  data policy service
  serves functions: apply-policy get-policy

Globals:
  Function:
    Timeout: 10
    Runtime: nodejs8.10
    Tags:
      app: solid-serverless
      domain: dev.yodata.io
    Environment:
      Variables:
        NODE_ENV: production
        DOMAIN: dev.yodata.io

Resources:
  'ApplyPolicyFunction':
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: index.applyPolicy
      FunctionName: 'apply-policy'
      AutoPublishAlias: next
