AWSTemplateFormatVersion: '2010-09-09'
Description: 'data policy service serves functions: apply-policy get-policy

  '
Globals:
  Function:
    Environment:
      Variables:
        CLIENT_ID:
          Ref: clientid
        DOMAIN: dev.yodata.io
        NODE_ENV: development
    Runtime: nodejs8.10
    Tags:
      app: solid-serverless
      domain: dev.yodata.io
    Timeout: 10
Parameters:
  clientid:
    Type: String
Resources:
  ApplyPolicyFunction:
    Properties:
      AutoPublishAlias: next
      CodeUri: s3://yodata-solid-serverless-data-policy/76591ab66c7af5e165bb032b11aa81f5
      FunctionName: apply-policy
      Handler: index.applyPolicy
    Type: AWS::Serverless::Function
  GetPoliciesFunction:
    Properties:
      CodeUri: s3://yodata-solid-serverless-data-policy/a2a8cec792af82cefb94286a5499b642
      FunctionName: get-policies
      Handler: index.getPolicies
    Type: AWS::Serverless::Function
  SetPolicyFunction:
    Properties:
      CodeUri: s3://yodata-solid-serverless-data-policy/77d6678c767bd5afb9aef715a02125fd
      FunctionName: set-policy
      Handler: index.setPolicy
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
