AWSTemplateFormatVersion: '2010-09-09'
Description: 'data policy service serves functions: apply-policy get-policy

  '
Globals:
  Function:
    Environment:
      Variables:
        CLIENT_ID:
          Ref: clientid
        DOMAIN: dev.yodata.io
        NODE_ENV: development
    Runtime: nodejs8.10
    Tags:
      app: solid-serverless
      domain: dev.yodata.io
    Timeout: 10
Parameters:
  clientid:
    Type: String
Resources:
  ApplyPolicyFunction:
    Properties:
      AutoPublishAlias: next
      CodeUri: s3://yodata-solid-serverless-data-policy/e80338bc24f9951b36be154ddae9acc8
      FunctionName: apply-policy
      Handler: index.applyPolicy
    Type: AWS::Serverless::Function
  GetPoliciesFunction:
    Properties:
      CodeUri: s3://yodata-solid-serverless-data-policy/35df50c432f4153622546364c5cdd421
      FunctionName: get-policies
      Handler: index.getPolicies
    Type: AWS::Serverless::Function
  SetPolicyFunction:
    Properties:
      CodeUri: s3://yodata-solid-serverless-data-policy/208c8b120aea49cc7f0f04f4d74307bb
      FunctionName: set-policy
      Handler: index.setPolicy
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
