AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'validate-schema JSON schema validation microservice

  '
Globals:
  Function:
    Timeout: 5
    Runtime: nodejs8.10
    Environment:
      Variables:
        NODE_ENV: production
Resources:
  ValidateSchemaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://yodata-solid-dev-solid-validate-schema/8288f298d7a5f691c97909b9934c639c
      Handler: index.handler
      FunctionName: validate-schema
