AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  validate-schema
  JSON schema validation microservice

Parameters:
  nodeEnv:
    Type: String
    Default: apply-policy
  svcHost:
    Type: String
  svcKey:
    Type: String

Globals:
  Function:
    Timeout: 30
    Runtime: nodejs12.x
    Environment:
      Variables:
        NODE_ENV:
            Ref: nodeEnv
        SVC_HOST:
            Ref: svcHost
        SVC_KEY:
            Ref: svcKey

Resources:
  'ValidateSchemaFunction':
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: index.handler
      FunctionName: 'validate-schema'
