event:
  properties:
    object:
      type: object
      description: the object to perform the action on - usually the request.body JSON content
    scope:
      type: object
      description: the ACL.scope to be applied
    policy:
      type: object
      description: >
        Pod level data polices to be applied.
        location = pod:settings/yodata/policy.json

DataPolicy:
  type: object
  properties:
    type: { type: 'string', enum: [] }
    processor: { type: 'string', enum: ['JsonSchema'] }
