AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'data policy service serves functions: apply-policy get-policy

  '
Parameters:
  clientid:
    Type: String
Globals:
  Function:
    Timeout: 10
    Runtime: nodejs8.10
    Tags:
      app: solid-serverless
      domain: dev.yodata.io
    Environment:
      Variables:
        NODE_ENV: development
        DOMAIN: dev.yodata.io
        CLIENT_ID:
          Ref: clientid
Resources:
  ApplyPolicyFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://yodata-solid-dev-solid-data-policy/56f50f5d4c2646b0d980b6b69dbd6c24
      Handler: index.applyPolicy
      FunctionName: apply-policy
      AutoPublishAlias: next
  GetPoliciesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://yodata-solid-dev-solid-data-policy/56f50f5d4c2646b0d980b6b69dbd6c24
      Handler: index.getPolicies
      FunctionName: get-policies
  SetPolicyFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://yodata-solid-dev-solid-data-policy/56f50f5d4c2646b0d980b6b69dbd6c24
      Handler: index.setPolicy
      FunctionName: set-policy
