AWSTemplateFormatVersion: '2010-09-09'
Description: 'data policy service serves functions: apply-policy get-policy

  '
Globals:
  Function:
    Environment:
      Variables:
        CLIENT_ID:
          Ref: clientid
        DOMAIN: dev.yodata.io
        NODE_ENV: development
    Runtime: nodejs8.10
    Tags:
      app: solid-serverless
      domain: dev.yodata.io
    Timeout: 10
Parameters:
  clientid:
    Type: String
Resources:
  ApplyPolicyFunction:
    Properties:
      AutoPublishAlias: next
      CodeUri: s3://yodata-hsf-data-policy/af944476564f44c7f6c99a6ef0b8aafa
      FunctionName: apply-policy
      Handler: index.applyPolicy
    Type: AWS::Serverless::Function
  GetPoliciesFunction:
    Properties:
      CodeUri: s3://yodata-hsf-data-policy/c9e8f18482b06740867245665d1e2888
      FunctionName: get-policies
      Handler: index.getPolicies
    Type: AWS::Serverless::Function
  SetPolicyFunction:
    Properties:
      CodeUri: s3://yodata-hsf-data-policy/b79f4267ea58c239fda0cf766d1e3b6c
      FunctionName: set-policy
      Handler: index.setPolicy
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
