AWSTemplateFormatVersion: '2010-09-09'
Description: 'data policy service serves functions: apply-policy get-policy

  '
Globals:
  Function:
    Environment:
      Variables:
        CLIENT_ID:
          Ref: clientid
        DOMAIN: dev.yodata.io
        NODE_ENV: development
    Runtime: nodejs8.10
    Tags:
      app: solid-serverless
      domain: dev.yodata.io
    Timeout: 10
Parameters:
  clientid:
    Type: String
Resources:
  ApplyPolicyFunction:
    Properties:
      AutoPublishAlias: next
      CodeUri: s3://yodata-rl-data-policy/726a7f537307464b78a3658e24dabc4a
      FunctionName: apply-policy
      Handler: index.applyPolicy
    Type: AWS::Serverless::Function
  GetPoliciesFunction:
    Properties:
      CodeUri: s3://yodata-rl-data-policy/262db74ff4e85667eb7af43c2d7efe54
      FunctionName: get-policies
      Handler: index.getPolicies
    Type: AWS::Serverless::Function
  SetPolicyFunction:
    Properties:
      CodeUri: s3://yodata-rl-data-policy/35091f9385c02247d7fede043f20b808
      FunctionName: set-policy
      Handler: index.setPolicy
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
