#!/usr/bin/env bash

# todo: update all the service deploy scripts to this template
# -----------------------------------------------------------
# Usage: IMPORTANT
#
#    Make sure your AWS_PROFILE is set to the right account!
#
#    > export AWS_PROFILE=<profile_name>
#
#    or for the one command only
#
#    > AWS_PROFILE=<profile_name> source deploy
#
#    ACCOUNT NAMES: | hsf | rl | solid |
# -----------------------------------------------------------

sam deploy \
--capabilities CAPABILITY_IAM \
--template-file template-package.yaml \
--stack-name create-view
