

AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: create-sfdc-contact stub
Globals:
  Function:
    Timeout: 30
    Runtime: nodejs12.x
    Environment:
      Variables:
        NODE_ENV: staging
Resources:
  ServiceFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: index.handler
      FunctionName: staging-create-sfdc-contact
