AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: solid-serverless api

Globals:
  Function:
    Timeout: 30
    Runtime: nodejs10.x
    Tags:
      app: solid-serverless
      component: api-middleware
    Environment:
      Variables:
        DEBUG_LEVEL: debug
        NODE_ENV: production
        CHECK_SCOPE_FUNCTION_NAME: check-scope
        CREATE_VIEW_FUNCTION_NAME: create-view
        APPLY_POLICY_FUNCTION_NAME: apply-policy
        DEFAULT_JSONLD_CONTEXT: 'https://dev.yodata.io/public/real-estate/context.json'

Resources:
  ApiMiddlewareFn:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: index.handler
      FunctionName: api-middleware
      AutoPublishAlias: next
    Policies:
      - AWSLambdaExecute
