AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  validate-schema
  JSON schema validation microservice

Globals:
  Function:
    Timeout: 5
    Runtime: nodejs8.10
    Environment:
      Variables:
        NODE_ENV: production

Resources:
  'ValidateSchemaFunction':
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: index.handler
      FunctionName: 'validate-schema'
