#!/usr/bin/env node
const inquirer = require('inquirer')
const sh = require('shelljs')

inquirer.prompt([
	{
		name: 'profile',
		message: 'aws profile?',
		default: process.env.AWS_PROFILE
	}
]).then(data => {
	sh.exec(`aws s3 mb s3://dev-yodata-io-echo-service --profile ${data.profile}`)
})

