AWSTemplateFormatVersion: '2010-09-09'
Description: 'echo-service returns event

  '
Globals:
  Function:
    Environment:
      Variables:
        NODE_ENV: production
    Runtime: nodejs8.10
    Timeout: 3
Resources:
  EchoService:
    Properties:
      CodeUri: s3://dev-yodata-io-echo-service/e77dcd2bce6ae4753e3ff73abc6a0239
      FunctionName: echo-service
      Handler: index.handler
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
