AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  {{cookiecutter.functionName}}
  {{cookiecutter.description}}

Globals:
  Function:
    Timeout: 3
    Runtime: nodejs12.x
    Environment:
      Variables:
        NODE_ENV: production

Resources:
  '{{cookiecutter.resourceKey}}':
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: index.handler
      FunctionName: '{{cookiecutter.functionName}}'
