AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  check-scope
  validates event.object with event.scope, adding event.isValid {boolean}

Parameters:
  clientid:
    Type: String

Globals:
  Function:
    Timeout: 6
    Runtime: nodejs12.x
    Environment:
      Variables:
        NODE_ENV: production
        DEBUG_LEVEL: debug
        CLIENT_ID:
          Ref: clientid

Resources:
  'CheckScopeFunction':
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: index.handler
      FunctionName: 'check-scope'
      Description: validates event.object with event.scope, adding event.isValid {boolean}
